/**
 * Bundle loader for the swarm worklet
 *
 * This re-exports the pre-bundled worklet generated by bare-pack.
 * The bundle includes all dependencies (hyperswarm, hyperdht, etc.) with constants inlined.
 *
 * To regenerate the bundle:
 *   npm run bundle:worklet
 *
 * Bundle source: apps/client/app/swarm-client.bundle.mjs
 * Generated wrapper: apps/client/src/worklet/swarmWorkletBundle.generated.ts
 */

export { SWARM_WORKLET_BUNDLE } from "./swarmWorkletBundle.generated";
